/**
 * NPMS Enterprise — Build script
 *
 * Generates config.js from environment variables before deploying.
 * On Vercel: environment variables are injected automatically.
 * Locally:   create a .env.local file (see .env.example) and run:
 *              node build.js
 *
 * config.js is gitignored — it is NEVER committed to source control.
 * The Supabase anon key is a PUBLIC key (safe for client-side use).
 * Security comes from Row Level Security (RLS) policies on the database.
 */

'use strict';
const fs   = require('fs');
const path = require('path');

// ── Load .env.local for local development ────────────────────────────────────
const envLocalPath = path.join(__dirname, '.env.local');
if (fs.existsSync(envLocalPath)) {
  const lines = fs.readFileSync(envLocalPath, 'utf8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx < 1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, '');
    if (!process.env[key]) process.env[key] = val;
  }
  console.log('Loaded .env.local');
}

// ── Read required variables ───────────────────────────────────────────────────
const url  = (process.env.SUPABASE_URL  || '').trim();
const anon = (process.env.SUPABASE_ANON_KEY || '').trim();

// ── Validate ─────────────────────────────────────────────────────────────────
if (!url || !anon) {
  console.error('');
  console.error('ERROR: Missing environment variables.');
  console.error('  SUPABASE_URL        =', url  ? '(set)' : '(MISSING)');
  console.error('  SUPABASE_ANON_KEY   =', anon ? '(set)' : '(MISSING)');
  console.error('');
  console.error('Create a .env.local file (see .env.example) or set Vercel environment variables.');
  console.error('');
  // Write an empty config so the app shows a "not configured" message
  // rather than a JS error — do not exit(1) so Vercel build can continue
  // with a warning.
  fs.writeFileSync(
    path.join(__dirname, 'config.js'),
    '// Generated by build.js — missing environment variables\nwindow.__NPMS_CONFIG__={};\n',
    'utf8'
  );
  process.exitCode = 1;
  return;
}

// ── Reject service_role key ───────────────────────────────────────────────────
if (anon.includes('service_role') || anon.length > 500) {
  console.error('ERROR: SUPABASE_ANON_KEY appears to be a service_role key.');
  console.error('Use the anon PUBLIC key only. The service_role key must never be in client code.');
  process.exitCode = 1;
  return;
}

// ── Write config.js ───────────────────────────────────────────────────────────
const configContent = [
  '// Generated by build.js — DO NOT EDIT MANUALLY',
  '// DO NOT COMMIT THIS FILE (it is in .gitignore)',
  `window.__NPMS_CONFIG__=${JSON.stringify({ url, anon })};`,
  '',
].join('\n');

const outPath = path.join(__dirname, 'config.js');
fs.writeFileSync(outPath, configContent, 'utf8');

// Verify the output does not accidentally contain a service_role key
const written = fs.readFileSync(outPath, 'utf8');
if (written.includes('service_role')) {
  fs.unlinkSync(outPath);
  console.error('SECURITY ERROR: config.js contained a service_role key. File deleted.');
  process.exitCode = 1;
  return;
}

console.log('config.js written successfully.');
console.log('  URL endpoint : ' + url);
console.log('  Anon key     : ' + anon.slice(0, 20) + '…(redacted)');

// ── Run verification ──────────────────────────────────────────────────────────
try {
  require('./scripts/verify-build.cjs');
} catch (e) {
  console.error('\nBuild verification failed:', e.message);
  process.exitCode = 1;
}
